### ISSUE TITLE
RAM Optimization

### ISSUE THREAD

**Issue by deB4SH** [deB4SH/OpenTransport#34]
Rework the entity-system for streets to keep the ram usage low
8c32144835ab31668a1ba15d5c73c5c2f506b530 uses about 500mb ram just for keeping all streets alive

**Comment by deB4SH** [comment]
![netbeans profiler image]{http://i.imgur.com/lMRDmcI.png}
here an image of the netbeans profiler for this project - we're on a heavy usage of char arrays

![testet on]{http://i.imgur.com/KV4ldrv.png}
used this design to test the usage

**Comment by N0V0S** [comment]
solved.

**Comment by deB4SH** [comment]
solved w/ 61cbb869efe83c6af85f4193b7db25a76d85fbe5
